repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, python, toml, json, markdown]
        args: ["--write", "*.yaml", "*.yml", "*.py", "*.toml", "*.json"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: "./tests/.*"
        args: ["--profile=black"]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        exclude: "./tests/.*"

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]

  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: poetry run pylint
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       args:
  #         [
  #           "--disable=import-error,wrong-import-order",
  #           "--rcfile=pyproject.toml",
  #         ]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.18.2
  #   hooks:
  #     - id: mypy
  #       exclude: "./tests/.*"
  #       additional_dependencies:
  #         [
  #           "mypy==1.18.2",
  #           "types-pyyaml>=6.0.12.20241230",
  #           "types-python-dateutil>=2.9.0.20250516",
  #           "types-tabulate>=0.9.0.20241207",
  #           "types-toml>=0.10.8.20240310",
  #           "types-requests>=2.32.4.20250913",
  #           "types-pytz>=2025.2.0.20250809",
  #           "types-tabulate>=0.9.0.20241207",
  #         ]

  # - repo: https://github.com/econchick/interrogate
  #   rev: 1.7.0
  #   hooks:
  #     - id: interrogate
  #       args: ["-c", "pyproject.toml"]
  #       files: "^.*/[src|tests]"
  #       pass_filenames: false
  #       always_run: true

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        stages: [pre-commit, manual]
        args: ["--fix", "--disable", "MD013,MD033,MD041,MD024,MD025"]
        types_or: [markdown]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: "^.*\\.(yaml|yml)$"

  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint
  #       args: ["-color"]
